added COC
GlobalTechTalks/TechTalksCOC- pull request #1
Opened 2018-12-30 14:20 UTC by Manas-kashyap

COC was given by forking @curiousLearner COC, and edited it accordingly

2018-12-31 20:28 UTC, utkarsh2102 requested changes

2018-12-31 20:28 UTC, utkarsh2102 commented on README.md
> +We want everyone to have a good time at our events. Be aware, be inclusive, be polite, be respectful and if you observe anything violating CoC, please report immediately to +91-96541 61510 or send me
I think it'd be better to include the email ID, too.

2018-12-31 20:28 UTC, utkarsh2102 commented on README.md
>  TechTalks Code of Conduct
Remove this line. Not needed.

2018-12-31 20:28 UTC, utkarsh2102 commented on README.md
>  # TechTalksCOC-
Rename this to:
`# TechTalks: Code of Conduct`

2019-01-03 15:56 UTC, Manas-kashyap commented on README.md
> +We want everyone to have a good time at our events. Be aware, be inclusive, be polite, be respectful and if you observe anything violating CoC, please report immediately to +91-96541 61510 or send me
send me email i will add it

2019-01-03 15:56 UTC, Manas-kashyap commented on README.md
>  TechTalks Code of Conduct
Okay sure

2019-01-03 15:56 UTC, Manas-kashyap commented on README.md
>  # TechTalksCOC-
okay anything else

2019-10-17 19:52 UTC, merged